// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5WpslyVoIGuNpKtKEy4NwQTqNIs6lams',
    appId: '1:446876370441:web:2747456003397cc88e9ad8',
    messagingSenderId: '446876370441',
    projectId: 'flutter-remote-204f8',
    authDomain: 'flutter-remote-204f8.firebaseapp.com',
    storageBucket: 'flutter-remote-204f8.appspot.com',
    measurementId: 'G-Y9NFEN7941',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMXFT2pBHNuuOZUSNqBvVrTdIv7ETYY84',
    appId: '1:446876370441:android:1f7edf67f538fc278e9ad8',
    messagingSenderId: '446876370441',
    projectId: 'flutter-remote-204f8',
    storageBucket: 'flutter-remote-204f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoGqSww4TzLyW-RvRph5qHLlPy7wo-ttA',
    appId: '1:446876370441:ios:25a28903d1efbaf18e9ad8',
    messagingSenderId: '446876370441',
    projectId: 'flutter-remote-204f8',
    storageBucket: 'flutter-remote-204f8.appspot.com',
    iosBundleId: 'com.example.remoteFlutter',
  );
}
